### ISSUE TITLE
Hardcode test repository

### ISSUE THREAD

**Issue by CianOG123** [cgreggtcd/SoftwareEngineeringMetrics#12]
A test repository needs to be added to the database/API so that we can get information to test our implementation.

Any repository can be used that has a large amount of activity.

**Comment by cgreggtcd** [comment]
This will also involve designing the real database! This will include the following tables:

1. Repository (which will in this case include only 1 row)
1. Branches 
    - Which repository they are from.
    - Details of pull requests from this branch
1. Commits
    - Time they were made
    - User they were made by
    - Branch they are from
    - Code added
    - Code changed
    - Code deleted
1. User 
    - Name

This comment will be updated with any other changes the database will undergo as more details come up regarding how this will be implemented. After these tables have been implemented, specialised functions for finding useful pieces of data will be implemented.

**Comment by hannahfoley-1** [comment]
Backend API meeting:
- Noel = Branch section of API
- Conall = User section of API
- Hannah = Repository and Commit sections of API

Using endpoints: https://docs.github.com/en/rest/overview/endpoints-available-for-github-apps

**Comment by cgreggtcd** [comment]
This will now rely on #25

**Comment by cgreggtcd** [comment]
A note for whoever is implementing the User API section - we will need a way to get the list of collaborators on a repository!
