### ISSUE TITLE
Create 'Time of commit' back-end

### ISSUE THREAD

**Issue by CianOG123** [cgreggtcd/SoftwareEngineeringMetrics#17]
A 'Time of commit' back-end needs to be created. This chart should display the time the times that someone is committing at and it should highlight if they are committing outside of working hours.

**Comment by hannahfoley-1** [comment]
Created a 2D String array which has an array of String arrays with both the author and time.

EG. { {"Hannah", "YYYY-MM-DDTHH:MM:SSZ"},
        {"Claire", "YYYY-MM-DDTHH:MM:SSZ"}}

Gets straight from API so will need to be changed when the database is up and running
