### ISSUE TITLE
Create work breakdown back-end

### ISSUE THREAD

**Issue by CianOG123** [cgreggtcd/SoftwareEngineeringMetrics#18]
A back-end needs to be created for the work breakdown chart. The work breakdown chart shows how many lines a code a user has added, removed and refactored.

**Comment by hannahfoley-1** [comment]
Created a 2D String array which has an array of String arrays with the author,  number of additions, number of deletions and number of changes

EG. { {"Hannah", "XX", "XX", "XX"},
{"Claire", XX", "XX", "XX"}}

Gets straight from API so will need to be changed when the database is up and running
