### ISSUE TITLE
Integrate database & API

### ISSUE THREAD

**Issue by CianOG123** [cgreggtcd/SoftwareEngineeringMetrics#25]
The database and API need to be integrated so that they can work together smoothly.

A design decision should be made on whether or not the database should store data longterm of it should be used as a cache. Whichever approach is easiest should be implemented.

**Comment by cgreggtcd** [comment]
Currently not planning on testing this as this is just a basic integration.

**Comment by cgreggtcd** [comment]
This is going ahead well in the [integration branch](https://github.com/cgreggtcd/SoftwareEngineeringMetrics/tree/dbapi-integration). Currently, data from a repository will just be initialised once. I  plan to implement a refresh function which will just delete all database entries associated with a specific repository and then reset them. 

Of course, integration for all the other database elements is also necessary. However, this requires the api implementation for the elements to be complete.

**Comment by cgreggtcd** [comment]
This was finished  a while ago.
