### ISSUE TITLE
Create API pull example

### ISSUE THREAD

**Issue by CianOG123** [cgreggtcd/SoftwareEngineeringMetrics#5]
### (Discovery task)

**An example program needs to be created pulling various data using GitHub API 3.0.**
The purpose of this task is to make the team aware of exactly what information can be pulled from GitHub. An example should be made of every type of data that you think we may use. This program will be used as a reference for the rest of the project for anyone looking to work with the API so it is important that it is clearly commented and set up in such a way so that we can copy the code in the future as needed into the main project. This program should be branched from main and it should remain in the branch. The example should never be merged into main or dev since it is only used for reference. The back-end team should inform everyone else when they discover that a type of data can be pulled using the API, so that they can model their solutions to their tasks around it.

### The program should:
    • Pull various data from a specified public repository using GitHub using GitHub API 3.0.
    • Be clearly commented and coded in a way that makes it easy to copy and paste the code elsewhere.
    • Print the data directly to the terminal (No UI required).
    • Relay what data can be pulled from using the API as soon as it is discovered so that other teams can 
       implement it in their tasks.

**@Hannahfoley-1 is in charge of this task but is not responsible for delegating work to the rest of the team.**

**Peter and Conall should contribute equal amounts of work as Hannah to this task.**

**Task should be completed by the start of the next sprint (Monday 14th November).**

**Comment by hannahfoley-1** [comment]
I think https://docs.github.com/en/rest/metrics should be a good place to start looking for the task assigned to us. This will give us a few stats just from using the API.

But there is also a huge list of all the data that can be pulled from GitHub using their API here : https://docs.github.com/en/rest/overview/endpoints-available-for-github-apps

Maybe if we all have a go trying to pull some of that metric data from the first link. There is a guide for getting started with the GitHub API here: https://docs.github.com/en/rest/guides/getting-started-with-the-rest-api

(Message pasted from Discord discussion)

**Comment by hannahfoley-1** [comment]
OK. I am able to get data from the GitHub API using the GitHub CLI. And there's a repo which (I think) does basically what we're trying to do. https://github.com/nicojs/spring-boot-github-api

(Message pasted from Discord discussion)

**Comment by cgreggtcd** [comment]
Closing as discovery phase is over.
