### ISSUE TITLE
Create mock UI features

### ISSUE THREAD

**Issue by CianOG123** [cgreggtcd/SoftwareEngineeringMetrics#6]
### (Discovery task)

**A mock UI needs to be created loosely based on the data that can be obtained from the API.**
The front-end team needs to create mock visualisations for the website. This should be used as a period of experimentation to get familiar working together and to create rough presets that can be modified and used once the algorithms have been decided upon.

### The visualisations should:
    • Utilise composite colour schemes.
    • Be professionally designed.
    • Be designed in such a way so that they are easy to modify for later use.
    • Feature animations and transitions if necessary.

This may be a useful resource for creating a composite colour palette:
https://webflow.com/blog/create-a-color-palette

Colours should be decided upon and they should be used strictly with no guessing or deviation in Hex codes.

**@louisclarkee is in charge UX  and colour scheme for this task.**

**Ali and Ying should focus on implementing features while Louis should focus mainly on tweaking the appearance to make them more professional. Louis should also inform Ali and Ying of any changes he feels should be made to the UI.**

**Task should be completed by the start of the next sprint (Monday 14th November).**

**Comment by cgreggtcd** [comment]
Closing as discovery phase is over.
