### ISSUE TITLE
Create algorithms

### ISSUE THREAD

**Issue by CianOG123** [cgreggtcd/SoftwareEngineeringMetrics#7]
### (Discovery Task)

**The features of our web-app need to be decided, and their algorithms need to be theorised**
The purpose of this task is to decide on what information will be displayed on the web-page. Algorithms should be decided upon now so that we have an idea of what is involved in implementing each feature, and so we can begin creating a concise UI for each feature.

### The algorithms should:
    • Make use of data obtained using the API example by the back-end team.

**@CianOG123 is in charge of this task.**

**Task should be completed by the start of the next sprint (Monday 14th November).**

**Comment by cgreggtcd** [comment]
Closing as discovery phase is over.
